### ISSUE TITLE
not working google assistant

### ISSUE THREAD

**Issue by boyseez** [Dimeiza/Assistants#27]
hi, you have do great work con the Assistant, i have try to install on my **Raspberry B+**, but not working, when i run google assistant
gives me a message: 

`pi@raspberrypi:~/Assistants $ ./startGoogleAssistant.sh
`
`INFO:root:Connecting to embeddedassistant.googleapis.com
`
`Traceback (most recent call last):
` 
`
 File "/home/pi/Assistants/env/bin/googlesamples-assistant-posixqueue", line 11, in <module> sys.exit(main())
`
 ` File "/home/pi/Assistants/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)`
 ` File "/home/pi/Assistants/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)`
 ` File "/home/pi/Assistants/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)`
`  File "/home/pi/Assistants/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)`
 ` File "/home/pi/Assistants/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/posixqueue.py", line 351, in main
    isOutput=False`
 ` File "/home/pi/Assistants/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers_for_queue.py", line 187, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.`
  `File "/home/pi/Assistants/env/lib/python3.5/site-packages/sounddevice.py", line 1264, in __init__
    **_remove_self(locals()))`
 ` File "/home/pi/Assistants/env/lib/python3.5/site-packages/sounddevice.py", line 681, in __init__
    samplerate)`
 ` File "/home/pi/Assistants/env/lib/python3.5/site-packages/sounddevice.py", line 2490, in _get_stream_parameters
    info = query_devices(device)`
 ` File "/home/pi/Assistants/env/lib/python3.5/site-packages/sounddevice.py", line 488, in query_devices
    raise PortAudioError('Error querying device {0}'.format(device))
sounddevice.PortAudioError: Error querying device -1`

instead when I start **./startAssistantControl.sh** the error is

`pi@raspberrypi:~/Assistants $ ./startAssistantControl.sh`
`Listening... Press Ctrl+C to exit
`
`connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
`
`attempt to connect to server failed
`
`Traceback (most recent call last):
` 
`File "AssistantControl.py", line 102, in <module>sleep_time=0.03)
` 
`File "/home/pi/Assistants/AssistantControl/snowboydecoder.py", line 176, in start stream_callback=audio_callback)
`  
`File "/home/pi/Assistants/env/lib/python3.5/site-packages/pyaudio.py", line 750, in open stream = Stream(self, *args, **kwargs)
`  
`
File "/home/pi/Assistants/env/lib/python3.5/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
`
`OSError: [Errno -9996] Invalid input device (no default output device)
`
can you help me solve the problem?
PS 
when i start alexa tells me  **# Alexa is currently idle! #**  but if tell but if I say the activation word doesn't respond, I don't know if it's normal? because I have to start also **./startAssistantControl.sh** or not.

PLEASE HELP MEEEEEEEEEEE

![Schizzo](https://user-images.githubusercontent.com/5839691/54869243-04a70a80-4d96-11e9-97ff-7e59eac77196.png)

**Comment by Dimeiza** [comment]
You must read notice of this repository before you open a issue. I wrote:

>If you have a trouble to execute this prototype, At first, you have to confirm that this problem is occured even if you follow official installation procedure. If so, You should send a issue to official team directly. It is earlier than sending issue me to resolve your problem.

>I don't receive a question how to execute Assistants in your environment.

You should try to install google assistant with official procedure and ask them why this problem caused.

And I guess:

>sounddevice.PortAudioError: Error querying device -1
> Invalid input device (no default output device) 

This problem is probably caused why sound device is inactivated or not proper.
